version: '3.1'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: espublicotech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"